language: python
python:
  - "3.6"
install:
  - pip install pytest
  - pip install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
  - pip install -r requirements.txt
  - python setup.py develop
script:
  - pytest tests
  - ./tests/test_shakespeare.sh
